### ISSUE TITLE
[Bug]:Logo and text are not align in center

### ISSUE THREAD

**Issue by URVESH1121** [imhardikdesai/SocioHub#27]
### Issue Summary

- On the Home page, there is a misalignment problem where the logo and text at the top-left are not centered as expected

### Steps to Reproduce

1. Go to Home page
2. See the Logo and text  at the top-left

### Expected Results

- The logo and text at the top-left of the Home page should be aligned in the center.

### Evidence
![image](https://github.com/imhardikdesai/SocioHub/assets/83448942/8a474a8e-eb9d-4d39-9e8c-176f01e5c21c)

**Comment by imhardikdesai** [comment]
Yes, You can Fix it @URVESH1121

**Comment by Abhi1234-tech** [comment]
@imhardikdesai @URVESH1121 is it fixed or should I work on it ?

**Comment by imhardikdesai** [comment]
> @imhardikdesai @URVESH1121 is it fixed or should I work on it ?

Hello, @Abhi1234-tech You can start working on it.

**Comment by Abhi1234-tech** [comment]
@imhardikdesai Done please check
