### ISSUE TITLE
Add Forget Password Page 

### ISSUE THREAD

**Issue by hardikd-zignuts** [imhardikdesai/SocioHub#29]
## Issue Title
Add Forget Password Page

### Background
In our current project, we do not have a "Forgot Password" page, which is a critical feature for user account recovery and security.

### Description
We need to implement a "Forgot Password" page that allows users to reset their passwords if they forget them. This page should include the following functionality:
- User should be able to enter their email address to request a password reset.
- An email with a reset link should be sent to the provided email address.

### Acceptance Criteria
- [ ] #30
- [ ] Password reset functionality.

## Additional Information
- Feel free to ask for clarification or help if needed.

## Labels
- Enhancement
- Security
- Help Wanted (if you want to encourage community contributions)

## Estimated Time
- 2-3 Days

## Attachments
[Code](https://chakra-templates.dev/forms/authentication#:~:text=Forgot%20Password%20Card)
![image](https://github.com/imhardikdesai/SocioHub/assets/124128351/203caea0-62f2-4927-9055-c99d200fc767)

## Discussion
Feel free to discuss any ideas, concerns, or suggestions related to this issue in the comments section.

/cc @imhardikdesai

**Comment by imhardikdesai** [comment]
> Should I try ?

Sure you can start working on it, I wil assign this issue

**Comment by A1X5H04** [comment]
How am I suppose to fill up the firebase credentials ?

**Comment by imhardikdesai** [comment]
> How am I suppose to fill up the firebase credentials ?

You can create your firebase project and add credentials in .env file in your local system. Just don't push that file

**Comment by A1X5H04** [comment]
I am sorry

> > How am I suppose to fill up the firebase credentials ?
> 
> You can create your firebase project and add credentials in .env file in your local system. Just don't push that file

I am sorry but I don't think I can contribute to it

**Comment by imhardikdesai** [comment]
> I am sorry
> 
> > > How am I suppose to fill up the firebase credentials ?
> > 
> > 
> > You can create your firebase project and add credentials in .env file in your local system. Just don't push that file
> 
> I am sorry but I don't think I can contribute to it

No worries ☺️, Thanks 👍
