### ISSUE TITLE
Setting Should be updated automatically

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/SocioHub#31]
### Description

Setting Should be updated automatically without click on save

### Scope

- ![image](https://github.com/imhardikdesai/SocioHub/assets/87645745/90a884cd-6537-455b-94dc-acf39a61121e)

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- Feature
- Responsive Design
- Hacktoberfest

**Comment by Kokonodray2001** [comment]
@imhardikdesai  . i would like to work on this issue can you please assign this to me.

**Comment by imhardikdesai** [comment]
@Kokonodray2001 Sure, Please start working on it

**Comment by Kokonodray2001** [comment]
@imhardikdesai  can you provide me with a test username and password to login? The create new user is not working.

**Comment by imhardikdesai** [comment]
@Kokonodray2001 Sure here is the credentials.
email:- johndoe@gmail.com
password:- john@123

**Comment by imhardikdesai** [comment]
Also if you are trying to run in local. so you need to set your firebase project then, you have to create a `.env` file like `.env.sample` then it will run on local environment

**Comment by Kokonodray2001** [comment]
Yes I did set the firebase it's running but the registration part is not working.. i mean I couldn't register as an new user

**Comment by imhardikdesai** [comment]
> Yes I did set the firebase it's running but the registration part is not working. I mean I couldn't register as a new user

Do you set up authentication in the Firebase console? if you can share the error screenshot then it will help me to resolve the problem.

**Comment by vivek-singh-13** [comment]
> @imhardikdesai can you provide me with a test username and password to login? The create new user is not working.

I am having same issue on the hosted website also. 
![image](https://github.com/imhardikdesai/SocioHub/assets/78148430/7c8df721-d139-44b4-b69e-68d4899f5a13)

**Comment by imhardikdesai** [comment]
I saw that in screen shot submit button is disabled so make sure you have entered all fileds. 
Because I just check in live website it is working fine for me

**Comment by vivek-singh-13** [comment]
Oh okay, I left the last name field empty. Now after filling it is working fine.

**Comment by Kokonodray2001** [comment]
I have created a Pr as per the requirement please check it #34
